### PR TITLE
Use custom struct for MapWith and MapInit

### PR DESCRIPTION
**Pull request by n1t0**
I am having an error because of the `impl FnMut(P::item) -> R` when trying to use `map_with` and `map_init`
```
error[E0277]: expected a `std::ops::FnMut<(std::result::Result<std::string::String, std::io::Error>,)>` closure, found `impl std::ops::FnMut<(<rayon::iter::par_bridge::IterBridge<utils::iter::Lines<std::io::BufReader<std::fs::File>>> as rayon::iter::ParallelIterator>::Item,)>`
   --> src/tokenizer/mod.rs:618:22
    |
618 |                     .map_with(
    |                      ^^^^^^^^ expected an `FnMut<(std::result::Result<std::string::String, std::io::Error>,)>` closure, found `impl std::ops::FnMut<(<rayon::iter::par_bridge::IterBridge<utils::iter::Lines<std::io::BufReader<std::fs::File>>> as rayon::iter::ParallelIterator>::Item,)>`
    |
    = help: the trait `std::ops::FnMut<(std::result::Result<std::string::String, std::io::Error>,)>` is not implemented for `impl std::ops::FnMut<(<rayon::iter::par_bridge::IterBridge<utils::iter::Lines<std::io::BufReader<std::fs::File>>> as rayon::iter::ParallelIterator>::Item,)>`
    = note: required by `rayon_cond::CondIterator<P, S>::map_with::{{opaque}}#0`
```

This is happening for a CondIterator that wraps a `std::io::Lines`, parallelized with `.par_bridge` using `CondIterator::into_parallel`.

Using a custom struct (as suggested in the comment above each method) allowed to make it work.

### CODE REVIEW

**Comment by cuviper** [comment]
Can you share a code snippet that demonstrated the problem before? I'd like to better understand how that failed.

**Comment by n1t0** [comment]
Sure! Thank you for taking the time to look at this!

For full context, we are trying to make the parallelism optional in a library that provides bindings to Python. Some of our users want to use the Python `multiprocessing` abilities, and in some cases, it forks the main process, leading to deadlocks when `rayon` initialized a thread pool before the fork. To achieve that, we would like to have traits that work just like the `IntoParallelIterator` from `rayon`, but that return `CondIterator` instead of the `ParallelIterator` (see https://github.com/huggingface/tokenizers/pull/311)

The snippet below should let you see the error I described. I'm compiling with `rustc 1.43.1 (8d69840ab 2020-05-04)`

```rust
use rayon::iter::IterBridge;
use rayon_cond::CondIterator;
use std::fs::File;
use std::io::{BufRead, BufReader};

pub trait MaybeParallelBridge<T, S>
where
    S: Iterator<Item = T> + Send,
    T: Send,
{
    fn maybe_par_bridge(self) -> CondIterator<IterBridge<S>, S>;
}

impl<T, S> MaybeParallelBridge<T, S> for S
where
    S: Iterator<Item = T> + Send,
    T: Send,
{
    fn maybe_par_bridge(self) -> CondIterator<IterBridge<S>, S> {
        let iter = CondIterator::from_serial(self);

        let parallelism = true;
        if parallelism {
            CondIterator::from_parallel(iter.into_parallel().right().unwrap())
        } else {
            iter
        }
    }
}

fn main() -> Result<(), std::io::Error> {
    let file = BufReader::new(File::open("/tmp/dummy-file.txt")?);
    let dummy: Option<bool> = Some(true);

    file.lines()
        .maybe_par_bridge()
        .map_with(&dummy, |dummy, line| println!("Process the line somehow"));

    Ok(())
}
```

**Comment by cuviper** [comment]
That's interesting -- it seems like the compiler is forgetting the constraint that `S::Item = P::Item`, because the expected/found types in the error should be identical. Maybe there is a loophole where that can't be totally proven, but I don't see it.

**Comment by n1t0** [comment]
Yes, I agree, that's why it didn't make sense to me at all. Do you think it might be a bug in the compiler?

**Comment by cuviper** [comment]
I think it probably is a bug in the compiler, or at least it might be a known limitation of the current type system. I started playing around with a smaller reproducer, not involving rayon, but didn't get around to filing an issue yet.

I also found that an alternate fix is to add a local parameter, like `map_with<F, T, R, Item>` with appropriate `where` clauses to make sure `P::Item` and `S::Item` match this. With the rest in terms of that local `Item`, it seems to work out.

Either way, we need to find a fix and add test cases, because apparently the current implementation doesn't work at all.

One advantage to sticking with `std::iter::Map` instead of our own iterator types is that `Map` has a lot of specializations. Some methods like `fold` we could also implement, but we can't do `try_fold` without stable `Try`, nor the unstable `TrustedLen` that helps optimizations elsewhere. Perhaps it's a premature optimization for me to worry about this, but it would be nice to keep taking advantage of that kind of thing.

**Comment by cuviper** [comment]
Hi -- Sorry I forgot about this, but I just took another look before I release a new version (#4). It seems current Rust does compile your example as-is, and that works back to 1.49. I'm not sure exactly what fixed it, but I'm encouraged that it was in the compiler alone.

I think I'd rather stick to using `Map` for now for all its specialization. Generally speaking, we could still use a lot of tests though!

**Comment by geofft** [comment]
For what it's worth, I built huggingface/tokenizers in February without this patch, with rustc 1.50.0 and rayon-cond 0.1 (as released on crates.io), and it built fine. So if this patch is only needed to fix the build, it does sound like it was a compiler bug that's no longer necessary to work around.

**Comment by cuviper** [comment]
Thanks for the feedback! I will leave it as-is for now, and I just published 0.2.

**Pull request closed without merging**
